/**
 * The agent context files, `.churnmap/HOTSPOTS.md` and `.churnmap/hotspots.json`: the top 20 in a
 * form any AI agent reads before editing. Pure (no `vscode`), shared by the extension and the MCP
 * server. Paths and numbers only.
 */
import { basename } from 'node:path';
import type { AnalysisResult, IgnoredFile, Trend, Window } from '../analysis/model.js';
import { bandOfFile } from '../analysis/bands.js';
import { type Band, bandLabel } from '../city/palette.js';
import { tableCell } from '../panel/markdown.js';

export const CONTEXT_DIR = '.churnmap';
export const HOTSPOTS_MD = 'HOTSPOTS.md';
export const HOTSPOTS_JSON = 'hotspots.json';

export const AGENT_RULES =
  'Before editing any file listed here, read this file. For those files: add or update tests ' +
  'first, keep diffs small and behaviour unchanged, and say in your summary which hotspot you ' +
  'touched.';

export const CONTEXT_FOOTER = 'Generated by Churnmap; regenerate with *Churnmap: Build city*.';

export interface HotspotsJsonEntry {
  rank: number;
  path: string;
  score: number;
  band: Band;
  /** The reasons as plain sentences. */
  reasons: string[];
  loc: number;
  commits: number;
  authors: number;
  trend: Trend;
}

export interface HotspotsJson {
  version: 1;
  generatedAt: string;
  repoRoot: string;
  head: string;
  window: Window;
  top: HotspotsJsonEntry[];
}

/** The top list in the shape both context files and the MCP server use. */
export function hotspotEntries(result: AnalysisResult): HotspotsJsonEntry[] {
  return result.top.map((h) => ({
    rank: h.rank,
    path: h.file.path,
    score: h.file.score,
    band: bandOfFile(h.file),
    reasons: h.reasons.map((r) => r.text),
    loc: h.file.loc,
    commits: h.file.commits,
    authors: h.file.authors,
    trend: h.trend,
  }));
}

export function renderHotspotsJson(result: AnalysisResult): HotspotsJson {
  return {
    version: 1,
    generatedAt: result.generatedAt,
    repoRoot: result.repoRoot,
    head: result.head,
    window: result.window,
    top: hotspotEntries(result),
  };
}

/** `HOTSPOTS.md`: what it is, the top 20 as a table, the rules, and how to regenerate it. */
export function renderHotspotsMd(
  result: AnalysisResult,
  ignored: readonly IgnoredFile[] = [],
): string {
  const entries = hotspotEntries(result);
  const lines = [
    '# Code hotspots',
    '',
    `The riskiest source files in ${tableCell(basename(result.repoRoot))}, ranked by Churnmap from the last ` +
      `${String(result.window)} days of git history (how often a file changes, how much, how deeply ` +
      `nested it is, how many people edit it and how many changes were fixes). Generated ` +
      `${result.generatedAt} at commit ${result.head.slice(0, 12)}.`,
    '',
  ];
  if (entries.length === 0) {
    lines.push('No hotspots in this window.', '');
  } else {
    lines.push('| # | File | Score | Band | Why |', '| --: | --- | --: | --- | --- |');
    for (const e of entries) {
      lines.push(
        `| ${String(e.rank)} | ${tableCell(e.path)} | ${String(Math.round(e.score))} | ${bandLabel(e.band)} | ${tableCell(e.reasons.join('; '))} |`,
      );
    }
    lines.push('');
  }
  if (ignored.length > 0) {
    lines.push(
      `Left out on purpose (ignored in Churnmap): ${ignored.map((e) => tableCell(e.path)).join(', ')}.`,
      '',
    );
  }
  lines.push('## Rules for AI agents', '', AGENT_RULES, '', '---', '', CONTEXT_FOOTER, '');
  return lines.join('\n');
}
